name: Auto Renew Server
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行
  workflow_dispatch:  # 允许手动触发

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
    - name: Execute command using Repo Secrets
      run: sshpass -p '${{ secrets.AUTO_RENEW_SERV00 }}' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -tt qingyuwuxi@s7.serv00.com "pm2 resurrect && exit" 
